name: Deploy Azure Function

on:
  push:
    branches:
      - main  # Change to your branch name if different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Azure Login # authenticate with Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"  # Adjust based on your function requirements

    - name: Install dependencies
      working-directory: backend
      run: |
        python -m pip install --upgrade pip --target=".python_packages/lib/site-packages"
        pip install -r requirements.txt --target=".python_packages/lib/site-packages"

    - name: Create deployment ZIP
      run: |
        cd backend
        zip -r functionapp.zip . -x "*.git*" "README.md"
        cd ..
        
    - name: Deploy to Azure Functions via CLI
      run: |
        az functionapp deployment source config-zip \
        --resource-group wake-function-apps \
        --name ${{ secrets.AZURE_FUNCTIONAPP_NAME }} \
        --src functionapp.zip
        
    - name: Logout from Azure
      run: az logout

