name: Deploy Azure Function App

on:
  push:
    branches:
      - main # Or your main development branch

env:
  BACKEND_PATH: './backend'
  FUNCTION_APP_PACKAGE_NAME: 'functionapp.zip'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python version
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Navigate to backend and install dependencies
      working-directory: ${{ env.BACKEND_PATH }}
      run: |
        ls
        pushd '${{ env.BACKEND_PATH }}'
        python -m pip install --upgrade pip
        pip install -r requirements.txt --target=".python_packages/lib/site-packages"

    - name: Zip function app files
      working-directory: ${{ env.BACKEND_PATH }}
      run: |
        zip -r ${{ env.FUNCTION_APP_PACKAGE_NAME }} .venv function_app.py host.json requirements.txt

    - name: Deploy to Azure Function App (Zip Push)
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Function App
      uses: azure/functions-action@v1
      with:
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        app-name: '${{ secrets.AZURE_FUNCTIONAPP_NAME }}'
        package: '${{ env.BACKEND_PATH }}/${{ env.FUNCTION_APP_PACKAGE_NAME }}'
        scm-do-build-during-deployment: true
        enable-oryx-build: true

    - name: Logout from Azure
      run: az logout